---
functional:
  - На сайте должна быть кнопка переключения на русский язык
  - Пользователь должен иметь возможность выбирать язык на котором будет писать бот
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - У имени пользователя должно быть ограничение по кол-во символов
  - У пароля должны быть ограничения по кол-во символов
  - Пароль должен состоять из символов и английских букв для большей безопасности аккаунта
  - В профиле у пользователя должно отоьражаться кол-во игр и их резульат
